export const ROUTES = {
  home: "/",
  subject: (slug: string) => `/subjects/${slug}`,
  quizPlay: (quizId: string) => `/play/${quizId}`,
  results: (attemptId: string) => `/results/${attemptId}`,
  leaderboards: "/leaderboards",
  leaderboardSubject: (subjectId: string) => `/leaderboards/subject/${subjectId}`,
  leaderboardQuiz: (quizId: string) => `/leaderboards/quiz/${quizId}`,
  daily: "/daily",
  dailyLeaderboard: "/daily/leaderboard",
  settings: "/settings",
  adminLogin: "/admin/login",
  adminDashboard: "/admin",
  adminSubjects: "/admin/subjects",
  adminQuizzes: "/admin/quizzes",
  adminQuestions: "/admin/questions",
  adminDaily: "/admin/daily",
  adminLeaderboards: "/admin/leaderboards",
} as const;
